import { VerticalBox, HorizontalBox, CheckBox, LineEdit, Button } from "std-widgets.slint";

export component IntervalInput {
    in property <string> label;

    HorizontalLayout {
        spacing: 10px;
        Text {
            text: label;
            vertical-alignment: center;
        }

        LineEdit {
            input-type: number;
            placeholder-text: "Duration in milliseconds";
        }
    }
}

export component Divider {
    in property <string> title;

    VerticalLayout {
        Text {
            text: title;
            height: 16px;
            horizontal-alignment: center;
            vertical-alignment: center;
            vertical-stretch: 0;
        }

        Rectangle {
            height: 2px;
            background: lightslategray;
            vertical-stretch: 0;
        }
    }
}

export component MainWindow inherits Window {
    title: "WayClicker";
    width: 300px;
    height: 300px;

    in-out property <bool> enabled: false;
    in-out property <string> interval-ms: 50;
    in-out property <string> keycode: 0;

    callback toggle-clicker();

    VerticalBox {
        Divider {
            title: "Clicker Settings";
        }

        IntervalInput {
            label: "Click Interval";
        }

        IntervalInput {
            label: "KeyCode";
        }

        Button {
            text: "Active";
            checkable: true;
        }

        Divider {
            title: "Server";
        }

        HorizontalLayout {
            spacing: 10px;
            alignment: space-between;
            Button {
                preferred-width: 135px;
                text: "Send settings";
            }

            Button {
                preferred-width: 135px;
                text: "Request settings";
            }
        }

        Button {
            text: "Enabled";
            checkable: true;
        }
    }
}
