import { VerticalBox, HorizontalBox, CheckBox, LineEdit, Button } from "std-widgets.slint";

export component IntervalInput inherits Window {
    in property <string> label;
    in-out property <string> input;

    HorizontalLayout {
        spacing: 10px;
        Text {
            text: label;
            vertical-alignment: center;
        }

        LineEdit {
            input-type: number;
            placeholder-text: "Duration in milliseconds";
            text <=> input;
        }
    }
}

export component Divider inherits Window {
    in property <string> label;

    VerticalLayout {
        Text {
            text: label;
            height: 16px;
            horizontal-alignment: center;
            vertical-alignment: center;
            vertical-stretch: 0;
        }

        Rectangle {
            height: 2px;
            background: grey;
            vertical-stretch: 0;
        }
    }
}

export component MainWindow inherits Window {
    title: "WayClicker";
    width: 300px;
    height: 300px;

    in-out property <bool> enabled: false;
    in-out property <bool> active: false;

    in-out property <string> interval: 50;
    in-out property <string> keycode: 0;

    callback send-server-packet();
    callback load-server-packet();

    VerticalBox {
        Divider {
            label: "Clicker Settings";
        }

        IntervalInput {
            label: "Click Interval";
            input <=> interval;
        }

        IntervalInput {
            label: "KeyCode";
            input <=> keycode;
        }

        Button {
            text: "Active";
            checkable: true;
            checked <=> active;
        }

        Divider {
            label: "Server";
        }

        HorizontalLayout {
            spacing: 10px;
            alignment: space-between;
            Button {
                preferred-width: 135px;
                text: "Send settings";
                clicked => send-server-packet();
            }

            Button {
                preferred-width: 135px;
                text: "Request settings";
                clicked => load-server-packet();
            }
        }

        Button {
            text: "Enabled";
            checkable: true;
            checked <=> enabled;
        }
    }
}
